// Script de génération du dictionnaire bilingue Lot 2 (FR / PT-BR)
// Regroupe les chaînes des 35 fichiers sous 4 sous-namespaces : carnet, reflex, progress, cards

import fs from 'fs';
import path from 'path';

const rawStrings = JSON.parse(fs.readFileSync('scripts/pedagogy_lot2_raw_strings.json', 'utf8'));

// Dictionnaire de traduction spécialisé Maracatu & Pédagogie musicale
const translationDictionary = {
  // --- CARNET D'AISANCE & DÉFIS RYTHMIQUES ---
  "Excellent ! Tu maîtrises le sujet.": "Excelente! Você domina o assunto.",
  "🔄 Rejouer": "🔄 Jogar novamente",
  "✕ Fermer": "✕ Fechar",
  "✅ Correct !": "✅ Correto!",
  "⚡ Défis Rythmiques": "⚡ Desafios Rítmicos",
  "🥁 Percussion": "🥁 Percussão",
  "💃 Danse": "💃 Dança",
  "Gonguê": "Gonguê",
  "Marcante": "Marcante",
  "Agbê": "Agbê",
  "Timbal": "Timbal",
  "← Retour au Carnet": "← Voltar ao Caderno",
  "maîtrisé": "dominado",
  "Maîtrisé": "Dominado",
  "Aucun défi d'entraînement actif pour cette saison.": "Nenhum desafio de treino ativo para esta temporada.",
  "Les programmes configurés dans sequenciador pour vos morceaux apparaîtront automatiquement ici.": "Os programas configurados no sequenciador para as suas músicas aparecerão automaticamente aqui.",
  "palier": "nível",
  "Ouvrir sequenciador sur votre prochain palier d'entraînement": "Abrir o sequenciador no seu próximo nível de treino",
  "Rejouer dans sequenciador": "Jogar novamente no sequenciador",
  "S'entraîner maintenant": "Treinar agora",
  "Réflexes & Conventions": "Reflexos & Convenções",
  "signaux validés (Maîtrisé)": "sinais validados (Dominado)",
  "signaux validés": "sinais validados",
  "À découvrir": "A descobrir",
  "Conducteur validé": "Condução validada",
  "Simulateur de signaux du Mestre avec arrêt au temps 1 et mémorisation de la structure chronologique.": "Simulador de sinais do Mestre com parada no tempo 1 e memorização da estrutura cronológica.",
  "Lancer le Défi Réflexe « Temps 1 » pour ce morceau": "Iniciar o Desafio de Reflexo «Tempo 1» para esta música",
  "Défi Réflexe": "Desafio de Reflexo",
  "Ouvrir la Timeline et compléter le conducteur à trous": "Abrir a Linha do Tempo e completar a condução com lacunas",
  "Conduire le morceau (Timeline)": "Conduzir a música (Linha do tempo)",
  "Répertoire de saison": "Repertório da temporada",
  "Testez vos départs au temps 1 sur les signaux du Mestre avec 4 choix de tablatures.": "Teste suas saídas no tempo 1 nos sinais do Mestre com 4 opções de tablatura.",
  "💃 Évalue ton aisance chorégraphique sur chacun des rythmes (toadas, pas de base, variations).\n              Les pas du Dançador seront bientôt intégrés ici pour t'entraîner visuellement.": "💃 Avalie sua fluência coreográfica em cada um dos ritmos (toadas, passos básicos, variações).\n              Os passos do Dançador serão integrados em breve aqui para o treino visual.",
  "Aucun rythme disponible pour le moment.": "Nenhum ritmo disponível no momento.",
  "⏱️ Entraînement :": "⏱️ Treino:",
  "Aucun chant disponible pour le moment.": "Nenhum canto disponível no momento.",
  "🎯 Quiz sur cette Toada": "🎯 Quiz sobre esta Toada",
  "Aucune fiche de culture disponible pour le moment.": "Nenhuma ficha de cultura disponível no momento.",
  "Aucune fiche de lutherie/atelier disponible pour le moment.": "Nenhuma ficha de lutheria/oficina disponível no momento.",
  "Atelier": "Oficina",

  // CarnetPercussionSection & DefisSummaryCard & Entrainement
  "⚡ Entraînements Sequenciad'Or": "⚡ Treinos do Sequenciador",
  "⚡ Défis": "⚡ Desafios",
  "Progression": "Evolução",
  "Défis Speed Trainer": "Desafios do Treinador",
  "Défis Réflexes": "Desafios de Reflexo",
  "Conducteurs à trous": "Conduções com lacunas",
  "paliers franchis": "níveis alcançados",
  "signaux maîtrisés": "sinais dominados",
  "morceaux validés": "músicas validadas",
  "Défis Rythmiques": "Desafios Rítmicos",
  "Défi Réflexe Mestre": "Desafio de Reflexo do Mestre",
  "Conducteur à Trous": "Condução com Lacunas",
  "Général": "Geral",
  "Global troupe": "Geral do grupo",
  "Assiduité & Pratique troupe": "Frequência & Prática do grupo",
  "Paliers franchis": "Níveis alcançados",
  "progression globale": "evolução geral",
  "Moyenne troupe": "Média do grupo",
  "BPM moyen visé": "BPM médio pretendido",
  "Taux de complétion": "Taxa de conclusão",
  "Élèves actifs": "Alunos ativos",
  "sur": "de",
  "inscrits": "inscritos",
  "Progression des Paliers de Tempo (Speed Trainer)": "Evolução dos Níveis de Andamento (Treinador)",
  "Palier": "Nível",
  "bpm": "bpm",
  "validé": "validado",
  "non validé": "não validado",
  "en cours": "em andamento",

  // --- REFLEX & CONDUCTOR ---
  "Temps 1 !": "Tempo 1!",
  "Écoute l'appel du Mestre...": "Escute o chamado do Mestre...",
  "Quelle est la tablature du Temps 1 ?": "Qual é a tablatura do Tempo 1?",
  "Chronomètre": "Cronômetro",
  "Précision": "Precisão",
  "Score": "Pontuação",
  "Essai": "Tentativa",
  "Manqué !": "Errou!",
  "Bravo !": "Parabéns!",
  "Temps écoulé": "Tempo esgotado",
  "Question suivante": "Próxima pergunta",
  "Voir les résultats": "Ver os resultados",
  "Défi Réflexe terminé !": "Desafio de Reflexo concluído!",
  "Recommencer le défi": "Recomeçar o desafio",
  "Quitter": "Sair",
  "Identifie le signal du Mestre": "Identifique o sinal do Mestre",
  "Geste du Mestre": "Gesto do Mestre",
  "Quel est ce signal ?": "Qual é este sinal?",
  "Convention": "Convenção",
  "Signal": "Sinal",
  "Mesure": "Compasso",
  "Choisir ce signal": "Escolher este sinal",
  "Valider la sélection": "Confirmar a seleção",
  "Retirer le signal": "Remover o sinal",
  "Timeline du morceau": "Linha do tempo da música",
  "Lecture audio": "Reprodução de áudio",
  "Pause": "Pausa",
  "Lecture": "Tocar",
  "Arrêt": "Parar",
  "Signal manquant à la mesure": "Sinal faltando no compasso",
  "Glissez ou cliquez pour poser le signal": "Arraste ou clique para posicionar o sinal",
  "Vérifier mon conducteur": "Conferir minha condução",
  "Tout est correct ! Conducteur validé !": "Tudo certo! Condução validada!",
  "Des erreurs ont été détectées. Corrigez les cases rouges.": "Foram encontrados erros. Corrija os compassos em vermelho.",

  // --- PROGRESSION & ANALYTICS ---
  "Évaluation": "Avaliação",
  "Auto-évaluation": "Autoavaliação",
  "Niveau de pratique": "Nível de prática",
  "Chants & Toadas": "Cantos & Toadas",
  "Toadas de saison": "Toadas da temporada",
  "Paroles & Structure": "Letras & Estrutura",
  "Rythme associé": "Ritmo associado",
  "Puxador / Rôle": "Puxador / Papel",
  "Tonalité": "Tonalidade",
  "Statistiques de chant": "Estatísticas de canto",
  "Taux de maîtrise": "Taxa de domínio",
  "Chants appris": "Cantos aprendidos",
  "Danse & Chorégraphie": "Dança & Coreografia",
  "Passes & Évolution": "Passos & Evolução",
  "Chorégraphies de saison": "Coreografias da temporada",
  "Pupitres de percussion": "Naipes de percussão",
  "Tableau de bord percussion": "Painel de percussão",
  "Membres par famille": "Integrantes por naipe",
  "Score moyen": "Média de pontuação",
  "Configuration des QCM": "Configuração dos QCM",
  "Gérer les distracteurs": "Gerenciar distratores",
  "Ajouter un leurre": "Adicionar distrator",
  "Leurres configurés": "Distratores configurados",
  "Type de quiz": "Tipo de quiz",
  "Nombre de questions": "Número de perguntas",
  "Durée par question": "Tempo por pergunta",
  "Statistiques des Roda Quiz": "Estatísticas dos Roda Quiz",
  "Taux de réussite global": "Taxa geral de acerto",
  "Participations": "Participações",
  "Questions répondues": "Perguntas respondidas",
  "Test à l'aveugle (Blind Test)": "Blind Test (Teste às cegas)",
  "Écoutez l'extrait et devinez": "Escute o trecho e adivinhe",

  // --- CARDS & SUPPORTS ---
  "Paroles du chant": "Letra do canto",
  "Voir les paroles complètes": "Ver a letra completa",
  "Traduction & Signification": "Tradução & Significado",
  "Notice culturelle": "Ficha cultural",
  "Origines & Histoire": "Origens & História",
  "Anecdotes de tradition": "Histórias da tradição",
  "Pièces & Composants": "Peças & Componentes",
  "Nomenclature": "Nomenclatura",
  "Progression de fabrication": "Progresso de confecção",
  "Outils nécessaires": "Ferramentas necessárias",
  "Guide d'apprentissage": "Guia de aprendizagem",
  "Documents pédagogiques": "Documentos pedagógicos",
  "Télécharger la fiche": "Baixar a ficha",
  "Session quotidienne": "Sessão diária",
  "Objectif du jour": "Meta do dia",
  "Signes & Gestes du Mestre": "Sinais & Gestos do Mestre",
  "Gestion des signaux": "Gestão de sinais"
};

console.log('Dictionnaire de base prêt. Analyse des chaînes brutes...');
